### ISSUE TITLE
Linux on Z dockerfile link is broken

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9-website#1]
On this page: http://www.eclipse.org/openj9/oj9_build.html

The link to the Linux on Z Dockerfile is missing the '3' in '390' :) .

**Comment by SueChaplain** [comment]
Problem fixed. Please re-test.

**Comment by SueChaplain** [comment]
@mstoodle  I'm unable to close this issue. I think it is a permissions problem on the repo as I can't see any of the configuration settings. Is there anything you can do please? I want to relocate the website here now that we've gone live because it will be easier for the community to contribute.
