### ISSUE TITLE
StackOverflow #OpenJ9 tag doesn't exist

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9-website#10]
This problem was pointed out by @kgibm at the eclipse/openj9 repository [here](https://github.com/eclipse/openj9/issues/32)

Here is the text from that issue:
```
The OpenJ9 landing page points to a StackOverflow search for the OpenJ9 tag; however, when I tried to submit a question with the OpenJ9 tag, StackOverflow said that I need to have at least 1,500 reputation to create a new tag.
```

I think we should change our link to just search for the text "openj9" until such time as the tag is warranted:
   https://stackoverflow.com/search?q=openj9

So that's just removing the # character from the link.

**Comment by kgibm** [comment]
Alternatively, it might be a good idea to find someone that has over 1,500 reputation to create the tag; otherwise, people might be hesitant to post.

**Comment by kartben** [comment]
I am happy to create the tag but I think there first needs to be a first question to tag.

**Comment by DanHeidinga** [comment]
Thanks @kartben.  I've created an openj9 question here: https://stackoverflow.com/questions/46283202/where-can-i-download-openj9-binaries-from

**Comment by kgibm** [comment]
Here is the question I wanted to post:

How do I compile OpenJ9 on Fedora/RHEL/CentOS?

The default [OpenJ9 build instructions](https://www.eclipse.org/openj9/oj9_build.html#prepare) use Docker, but I'd like to compile without Docker; specifically, on RHEL 7.3.

I also figured out the answer to it that I can post up.

**Comment by kartben** [comment]
there you go :) https://stackoverflow.com/questions/tagged/openj9

**Comment by kgibm** [comment]
@kartben Hmm, that didn't seem to create the tag. When I tried to create a new question and typed openj9 in the tags and clicked submit, it still says, "Creating the new tag 'openj9' requires at least 1500 reputation. Try something from the existing tags list instead." Could you try creating the question?

**Comment by kgibm** [comment]
It's been created, thanks! I believe this issue can be closed now.

**Comment by kartben** [comment]
Great!

**Comment by DanHeidinga** [comment]
Thanks @kartben & @kgibm for your help with this.
