### ISSUE TITLE
Enhance FAQ

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9-website#11]
Based on the [reddit post](https://www.reddit.com/r/programming/comments/70g4z7/ibm_has_open_sourced_its_own_jdk_as_eclipse_openj9/) about OpenJ9, as well as twitter traffic, there's definitely some entries missed in the FAQ. 

* What does J9 Mean? Does it have to do with Java 9? 
* Does it support all of Java, or just some subset? (_i.e_, is it missing `com.sun.*`?) 
* What's the relationship to Eclipse? (Foundation, IDE)
* Should I expect OpenJ9 to outperform OpenJDK with hotspot out of the box?

**Comment by kartben** [comment]
* What license is OpenJ9 made available under? (see https://stackoverflow.com/questions/46295129/eclipse-openj9-license)

**Comment by mstoodle** [comment]
The licensing question should have a complete answer. Something like:

The project license is EPL V2 and Apache 2.0 (you can choose) but the EPLv2 license has a secondary compatibility for the GPLv2 used by OpenJDK so you can combine the two projects and be able to use them together (as OpenJDK's GPLv2 of course).

The license is documented in the LICENSE file at https://github.com/eclipse/openj9/blob/master/LICENSE, and the license is summarized at the top of virtually every file in the github.com/eclipse/openj9 repository, e.g.:

```
    /*
     * ...
     * This program and the accompanying materials are made available under
     * the terms of the Eclipse Public License 2.0 which accompanies this
     * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
     * or the Apache License, Version 2.0 which accompanies this distribution and
     * is available at https://www.apache.org/licenses/LICENSE-2.0.
     *
     * This Source Code may also be made available under the following
     * Secondary Licenses when the conditions for such availability set
     * forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
     * General Public License, version 2 with the GNU Classpath
     * Exception [1] and GNU General Public License, version 2 with the
     * OpenJDK Assembly Exception [2].
     *
     * [1] https://www.gnu.org/software/classpath/license.html
     * [2] http://openjdk.java.net/legal/assembly-exception.html
     *
     * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
     */
```

**Comment by SueChaplain** [comment]
2 new FAQs are added to the website to cover:
- What license?
- What does the J9 stand for?

@mgaudet your initial issue covered some other questions too. 

**- Does it support all of Java, or just some subset? (i.e, is it missing com.sun.*?)**
What do we want to say here? What capabilities are missing without them?
Q: "Does an OpenJDK built with OpenJ9 include everything I get in an Oracle binary?
A: No, not everything. Oracle add some packages (com.sun.*) on top of the OpenJDK class libraries that support additional capabilities. This is  value-add that you pay for over a free OpenJDK binary.

**- What's the relationship to Eclipse? (Foundation, IDE)**
I think the website is super clear that this is a project that belongs to the Eclipse Foundation. Is this not already covered by "Why did IBM contribute their J9 virtual machine to the Eclipse Foundation?" .. or do we think we have to spell out that the Eclipse Foundation is an "organisation" as opposed to the thing that it is most well known for - Integrated Development Environment (IDE). That seems like something that is just too basic to clog up our FAQ.

**- Should I expect OpenJ9 to outperform OpenJDK with hotspot out of the box?**
@vijaysun-omr .... how should we handle this one? I'm sure the answer is "yes", but adding any stats would be a point in time statement that we'd have to revisit regularly. Any suggestions?

**Comment by pshipton** [comment]
All the same packages provided by OpenJDK are part of OpenJ9. Some of these classes don't work because OpenJ9 doesn't provide the back end implementations atm. Off the top of my head, OpenJ9 doesn't support com.sun.management.DiagnosticCommandMBean, HotSpotDiagnosticMXBean, ThreadMXBean, VMOption. sun.jvmstat.* (the jdk.jstatd and jdk.internal.jvmstat modules), sun.tools.* (the jdk.jcmd module). There may be more.

**Comment by vijaysun-omr** [comment]
@SueChaplain Yes we will be giving you performance numbers within the next day or two so that it can be added to the OpenJ9 website next week. I will reach out to you with the data and we can work together. And yes it will have to be re-measured periodically.

**Comment by vijaysun-omr** [comment]
@SueChaplain could you please add a link to the Performance related articles we had published earlier in the year to the OpenJ9 landing page ? Would be useful to have people take a look if they want a bit more info to read (that article is linked to a bunch of other articles, so it's probably a good one to use).

**Comment by SueChaplain** [comment]
@vijaysun-omr Good idea. I created issue #18 to address the performance related articles

**Comment by SueChaplain** [comment]
Q&A needed for users who find that OpenJDK with OpenJ9 performs differently than expected.
Input received from Vijay.

**Comment by SueChaplain** [comment]
"Graveyarding" this issue. I believe the set of FAQs we have covers most people's needs and has satisfied the initial confusion over what OpenJ9 is and isn't. If we believe further Q&As are needed, we can open new issues.
