### ISSUE TITLE
Create hyperlinks for front page banner headlines

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9-website#115]
Could we update the "Lower memory footprint" "Fast startup time" and "High application throughput" so that they are links directly to the relevant sections of the performance data page that back up those statements?

**Comment by SueChaplain** [comment]
This was tried, but created a UX issue as you could not see where one link started and another ended. A compromise was found by adding a link to "evidence" under the headings.
See https://github.com/eclipse/openj9-website/pull/121

Closing this issue
