### ISSUE TITLE
Add an obvious "See who's using OpenJ9!" link to home page

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9-website#116]
We can obviously list that IBM uses it for its enterprise stack. Maybe we can also afford a link to IBM's support offering that's available here.

There are a few other projects we should reach out to, to see what, if anything, they'd be willing to have listed on such a page: Apache OpenWhisk, Linkerd has experimental support, etc.

**Comment by mstoodle** [comment]
Capturing links to favourable tweets people would help too

**Comment by mstoodle** [comment]
Best kinds of references would be less "we're using it too!" and more "we're using it for X because of Y"... So hopefully a little bit deeper than "just" a high level marketing bullet.

**Comment by mstoodle** [comment]
...and include SPEC benchmark results, like: https://www.spec.org/jEnterprise2018web/results/res2018q3/jEnterprise2018web-20180913-00002.html

**Comment by SueChaplain** [comment]
@vijaysun-omr - the performance page is due an update. We blogged about the Eclipse IDE performance a while ago but it is missing from the main page. I'd like us to re-design the performance page to summarise all the different scenarios and move more words to the supporting markdown files that house the data. i.e. make the page more visual and less wordy. Incorporating the benchmark links is a great idea for this page too.

I'll try and shift the work up our priority list :-/

**Comment by SueChaplain** [comment]
See #147. Closing this in favour of the new issue raised by Sean specifically for this purpose but in the context of the new re-design.
