### ISSUE TITLE
Migrate website content to this repo

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-website#12]
Current the website content is hosted directly on the Eclipse git repos (I think), but the content should live here so that it is easier for contributors to open pull requests.

**Comment by SueChaplain** [comment]
@DanHeidinga we have always planned to do this. We needed to ensure that we could go live without delays and hosting in the Eclipse git was the easiest "one step" approach. When we move the content to this repo we will add the "second step" to work from here and mirror to Eclipse git. First step to achieving this is to be able to do anything in this repo ... I seem to have no permissions :-(

**Comment by mstoodle** [comment]
Hi @SueChaplain are you saying you don't seem to have committer status in this repo?

**Comment by mstoodle** [comment]
Even if you don't, I appear to, so you can still make contributions (pull requests) until we sort out your permissions issue...

**Comment by SueChaplain** [comment]
Hi @mstoodle - I don't have a settings tab for the repo, so I can't set up any keys or webhooks. No point having the primary repo here until we can automate the publication of the site via the Eclipse Git repo. I'm hoping to use the Eclipse JIPP for OpenJ9 to orchestrate the publication based on merges. I'm guessing I need to be made an owner of the repo. At the moment I can't even close an issue (although Esther can).

**Comment by mstoodle** [comment]
Oh, i see. Actually, nobody has admin access to these repositories because they're run by Eclipse. We can request anything you want by opening bugs at Eclipse. Do we have your correct email address on file with Eclipse in our committer list (see https://projects.eclipse.org/user/8832 is the link from our project page for you as a committer)

**Comment by mstoodle** [comment]
As a committer, you should have the same access we all have to the JIPP instance at ci.eclipse.org/openj9 (but it's WIP: we're still getting the plumbing set up there!). We should be able to set up any jobs you need there.

**Comment by SueChaplain** [comment]
Thanks @mstoodle . I've opened a bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=522530 and hopefully asked for the right things. Small progress.

**Comment by DanHeidinga** [comment]
@SueChaplain Any update on this?

If we're not able to get the automation in place quickly, can we master the website here and manually mirror it to the eclipse git?  While it's a small pain to do, it makes it 100x easier for people to make website changes.

**Comment by AdamBrousseau** [comment]
I have pushed the contents of the eclipse repo used for the website to this repo.
I have helped @SueChaplain setup PR builds to test changes on the staging server. It seems to be working but I would like her to take a look. Once we are happy with it, the second job to push this repo's master branch to the eclipse repo should be easy to setup.

**Comment by AdamBrousseau** [comment]
I have setup the [Jenkins job](https://ci.eclipse.org/openj9/view/Infrastructure/job/Mirror-OpenJ9-Website-to-Eclipse) to mirror this Github repo into the Eclipse repo. It is currently running in the **reverse** direction every 15 minutes. Once we are ready to switch over to work in Github, I can change it back.

**Comment by SueChaplain** [comment]
The team here are preparing to move to github.com/Eclipse/openj9-website as the primary repository next week. (There have been ongoing requests to update site content during JavaOne, as expected). I've asked everyone to fork & setup local clones with the correct remote in place this week. @AdamBrousseau - when would be a good time for you to modify the current Jenkins sync to reverse the flow please? We will need to ensure that all work in progress is committed or migrated to our new local clones.

**Comment by AdamBrousseau** [comment]
I can make the change on Tuesday (or earlier if needed). It should be a quick modification.

**Comment by SueChaplain** [comment]
The team here are set for Tuesday. We will ensure that all our changes are committed and we have forks ready to work on. @AdamBrousseau please signal when you are about to make the switch.

**Comment by AdamBrousseau** [comment]
The mirror is now going from Github to Eclipse. Please do not commit any new content directly to the Eclipse repo. The mirror runs on a polling interval of 5 minutes. I will keep an eye on it to make sure it is working properly. I would also like to commit the Jenkins pipeline code in a Jenkins file to this repo. I will open a PR once I have confirmed everything is working as expected.

**Comment by DanHeidinga** [comment]
That's great news!  Thanks @AdamBrousseau, @SueChaplain and co for getting this mastered here.

**Comment by DanHeidinga** [comment]
Thanks @AdamBrousseau for getting all the automation set up and the Jenkins build scripts committed here!
