### ISSUE TITLE
Homepage Redesign for OpenJ9

### ISSUE THREAD

**Issue by SeanC1083** [eclipse/openj9-website#124]
Overview of homepage redesign

![openj9_palettes](https://user-images.githubusercontent.com/41338985/47126337-271c8100-d256-11e8-8d31-de1386978170.jpg)

**Comment by fjeremic** [comment]
Wow these look really nice! I'm a big fan of the first one as the contrast between the colors is pleasing to the eye.

**Comment by mstoodle** [comment]
Please note that the design is 100% a mock-up, so does not reflect any actual endorsement of OpenJ( by anyone (at least, that I'm aware of).

**Comment by TreeHanh** [comment]
Thank you all for the feedback! This is a first pass of the redesign so it's great to hear all your thoughts. 

We are creating a version that uses the current logo so please stay tuned in for that :).

**Comment by SeanC1083** [comment]
@kartben Do you know if there are any members that currently meet all of these conditions? 

I know that we are definitely interested in displaying sponsors and other organizations that are either supporting or using OpenJ9 - as our research findings show that it can help convince new orgs/users to try the product.

**Comment by SeanC1083** [comment]
Here is a zoomed in mockup of this redesign that includes UX Annotations...I would love to get some feedback around the proposed UX changes. Thanks!

[OpenJ9 Redesign UX with Annotations.pdf](https://github.com/eclipse/openj9-website/files/2500228/OpenJ9.Redesign.UX.with.Annotations.pdf)

**Comment by SeanC1083** [comment]
I am including a UX Mockup for this redesign that I would love to get feedback on! Thanks! 
[OpenJ9 Redesign UX with Annotations.pdf](https://github.com/eclipse/openj9-website/files/2500232/OpenJ9.Redesign.UX.with.Annotations.pdf)

**Comment by pshipton** [comment]
Definitely an improvement over the current webpage. Took me a while to spot the Download and Docs buttons at the top, but I expect they would be easier to spot on the website than scrolling around a .jpg

**Comment by pmhayward** [comment]
@SeanC1083 - I like the look of the current mockup, but have a few comments/questions...
1. Please bear in mind that the current website was created with limited resources, time, and expertise. (And we are maintaining it on a similar basis!) Unless suitable resources become available, this GitHub issue is likely to remain frozen in the "icebox"! Importantly, any design/implementation needs to be sufficiently simple to enable mere mortals to make tweaks and updates without always needing the help of an experienced FE developer.
2. The color palette used on the current web pages was derived from the colors used by the Eclipse Foundation because this is an Eclipse project and these web pages are part of the Eclipse website. If maintaining this similarity is no longer thought important, then fine. But if it is, could we have a mockup that uses the current Foundation color palette?
3. As already mentioned, the OpenJ9 logo is problematic in this mockup. Apart from the fact that the current logo  ![image](https://user-images.githubusercontent.com/20087447/47363816-a1725880-d6cf-11e8-81c6-2ab1f4f40c7d.png) was arrived at after some pain(!), it probably shouldn't be changed just as it's becoming established - and certainly not without approval from Eclipse as it now 'belongs' to the Foundation.
4. AFAIK, IBM is the only company that matches the Eclipse criteria for displaying a logo (https://github.com/eclipse/openj9-website/issues/124#issuecomment-431149586) and IBM would therefore have the only logo in that section. Apart from looking a bit silly on its own, it probably doesn't give the best message for something that is trying to establish itself as 'open' source!
5. The current website is designed to scale (reasonably) well between widescreen and mobile devices. Could we see a mockup of how you would envisage this page appearing on a small screen?

**Comment by SeanC1083** [comment]
thanks for the feedback @pshipton and @pmhayward -- if you have other feedback and know some people who might, let us know. Hey @TreeHanh FYI on these comments.

**Comment by SueChaplain** [comment]
@SeanC1083 @TreeHanh 

- Please can you remind me of where "GET STARTED" leads you? (I *think* the intention was to link to the AdoptOpenJDK site, which would take users straight off to another site before they had explored anything. If so, we probably need to add words/change the button description accordingly). 
- Re. "who's using". Openwhisk was mentioned as a possibility, but this would not meet Eclipse's strict logo requirements. Infact, I think it will be difficult to find any customers going forward that would fit the criteria that @kartben references from the handbook. We might need to re-think how this section works. I really like the way it is done here: https://www.elastic.co/use-cases ..... although logos would still be a no-no.
- In support of @pmhayward comment on colours, would black and orange work, with the teal logo? All those colours are part of Eclipse standard palette and ones we have worked into the (separate) user docs. (I think we should steer clear of the blue, which reminds me of an IBM site .... although actually the OpenJ9 blog is blue)

**Comment by SeanC1083** [comment]
1st bullet point: @SueChaplain yes, that button leads to the Adopt page, additionally, we are planning to change the wording from Getting Started to something else, like - Get OpenJ9 or Get JVM or Download JVM; or Download OpenJ9 -- any suggestions? 

@TreeHanh can speak to the 2nd and 3rd bullet points.

**Comment by TreeHanh** [comment]
@SueChaplain Here are two different designs with the the original teal logo and teal palette. 

![openj9_homepage](https://user-images.githubusercontent.com/18586040/47747115-f1b46200-dc5d-11e8-957f-a2e153894671.jpg)
![openj9_homepage2](https://user-images.githubusercontent.com/18586040/47747314-7a330280-dc5e-11e8-9a08-941cb8b38582.jpg)

**Comment by fjeremic** [comment]
> Please can you all take a moment to think about what we have at our website today when you are considering this design and raise any requirements now. The current OpenJ9 website has been updated many times since its inception to add/amend content, taking it from what was quite a simple design to something that is now rather bloated with buttons, links and words. If we agree that the current design is good and we find the resource to implement it, I'd hate us to start making changes that might compromise it. So .... is there anything missing?

Personally I think the proposed design here is much better than what we have. I find it easier to read and navigate than our current website. I'll echo @pmhayward's concern raise in his point 5. above. I'm not sure how the proposed design looks on mobile. Our current website does not 100% mobile-friendly but it's readable, more or less.

**Comment by TreeHanh** [comment]
Hi everyone. You can find the mobile design above along with some minor changes to the OpenJ9 homepage. We've added a "Read User Stories" button that leads to a page that details customer engagement using OpenJ9. We've also changed some wording in the "community" and "participation" section. Please feel free to read through the texts and let us know if there's anything to change. Thanks!

**Comment by DanHeidinga** [comment]
Does the `contribute` link go to GitHub?  

I don't see the "Join Slack" link in the redesign.  Oversight?

**Comment by TreeHanh** [comment]
The "Join Slack" link is in the button under "Join the OpenJ9 Community". It reads "OpenJ9 Slack". We could add the logo to the button if that makes it more clear.

**Comment by DanHeidinga** [comment]
Thanks for the clarification.  My confusion is from the difference with the current website which treats that as two buttons - one to join and one to open slack.

**Comment by SeanC1083** [comment]
@DanHeidinga so the slack button will take the users to a page where they can either login or signup for the slack channel. It will require some code changes but it's pretty minimal I believe. So to answer you're question...it will serve both purposes.

**Comment by SueChaplain** [comment]
@SeanC1083 - 

You asked if I thought we'd got all the feedback we were going to get. As promised, I've done a side-by-side comparison and also looked at features/updates people have asked for that are not accommodated in the current design. Hopefully this will highlight differences for others and perhaps identify any important omissions:

1. Buttons we currently have that take users to content elsewhere

- what's new (release highlights)
- Blog (wordpress - there's lots of good content here, so I think we want it an obvious link)
- User documentation (we are asking people to download but what if they want to know how to use it?)
- FAQ (high level orientation .. what is OpenJ9 etc)

Is the intention to put these things only in the menu?

2. Are you assuming that the Resources page remains in the menu?

3. You have 2 areas "Join the OpenJ9 community" (slack & mailing list) and "Participate in the OpenJ9 community" (build & Contributors guide)

** JOIN**

- **Slack** - taking users to a page where they either sign up or link to Slack might be annoying for people who have already signed up but need to click twice to get there (although perhaps once people join they will use the slack client instead)
- **Mailing list** - this is probably the least used way of connecting to the community and is a little archaic. I'd also say that the mailing list is probably more for people who want to participate, so if we want it we should probably move it down to "participate". For "join", I think I'd prefer to see something about the OpenJ9 community calls that we run every week as an alternative. Or "What's new" or "Blog".

**PARTICIPATE**

- **Build** - not sure what this has to do with "participating". People might want to build it but not participate in the project. I'm not sure Build fits in either "join" or "participate". So does this become another menu item?
- **Contributors guide** -  Good!  

4. Request history

The following items have been requested in the past or are on the current open issues list, but are not accommodated in the design. Are they still important?

- put the developer platforms on the front page so people know what we support. (Linux, Windows, macOS)
- link to our support statement on the front page (https://github.com/eclipse/openj9-docs/issues/38)
- advertise our regular hangouts
- link to our release plans at Eclipse Foundation

**Comment by SeanC1083** [comment]
Thanks for sharing this feedback. I have a few follow-up questions: 

Buttons: 

Q: _What does this mean: "_User documentation (we are asking people to download but what if they want to know how to use it?)"

FAQ: 

A: We are planning to put FAQ in the footer, do you have any concerns about that that I can address?
I've also am planning to link to it from the Resources page. 

Nav Options: 

Yes, Resources will likely be a navigation option. I'm currently thinking 'About' 'Resources' 'Docs' 'News' (possibly 'Download'

Join: 

For Slack we are probably going to do something similar to https://www.kitura.io/ which does take them to a different page. I will look into it to see how we might go about reducing the number of interactions a user has to do before they can get up and rolling with Slack. 

For Mailing list we thought that providing a link to sign up on the homepage would give it enough exposure. Given that you believe the Mailing List is about participating, instead of joining, where do you see this falling as it relates to when in the user journey they might want to sign up for the mailing list?

Participate 

I agree that Build should not appear under Participate -- just to clarify the only way users can contribute to OpenJ9 is content changes and other low level updates to the site.  

Docs might be the header label that replaces contributors guide...thoughts?

Request history:

Each of these bullets points would be easy to incorporate: 

- putting the developer platforms on the front page so people know what we support. (Linux, Windows, macOS)

- link to our support statement on the front page (eclipse/openj9-docs#38)

- advertise our regular hangouts

- link to our release plans at Eclipse Foundation


**Everything I didn't speak to I agree with and will work on/think about these changes/updates. FYI*

**Comment by SueChaplain** [comment]
Final design:

Note: For updated header / footer see #156


![Updated Desktop Designs Post_Feedback](https://user-images.githubusercontent.com/18395037/66748691-bbc4b980-ee7f-11e9-8a14-fb0224a828ac.jpg)
![Mobile Designs Post_Feedback](https://user-images.githubusercontent.com/18395037/66748704-c54e2180-ee7f-11e9-9427-cc3cc5572cb7.jpg)
