### ISSUE TITLE
Link to "How did Open J9 get its name" 

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9-website#14]
https://medium.com/@rservant/how-did-the-j9-in-openj9-get-its-name-95a6416b4cb9

Would be a useful FAQ entry :)

**Comment by SueChaplain** [comment]
Think we can close this as a duplicate of issue #11, bullet "What does J9 Mean? Does it have to do with Java 9?" ... we can embed a link there.

**Comment by doveye** [comment]
Closing as duplicate of issue #11
