### ISSUE TITLE
Enabling Google Analytics for project data collection 

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#141]
Eclipse Foundation are allowing the use of Google Analytics to collect data on project websites, provided we accept their new policy, allow the webmaster access to the profile, and don't break any rules:

https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

I would like to implement Google Analytics (GA) for the website and user docs so that we can start to look again at website traffic and make data-driven decisions about content/placement etc.

According to Eclipse rules, when you enable GA you must anonymize the IP address, which looks pretty straightforward. If we do this, I don't believe we are storing any personal identifiable information (PII).

@mstoodle @DanHeidinga @pshipton 
As project leads, please can you read the policy, consider whether I have covered all the bases, and +1 or -1 to proceed.

Looking at the policy, I believe we can provide the answers in *italics*:

>1) If your service stores Personally Identifiable Information (PII) data you must subscribe to
eclipse.org-gdpr@eclipse.org , and respond within 30 days to requests to delete
accounts or make user data available to the specific user in question. The IP address of
a client request is considered PII.

*Google Analytics IP data will be anonymized. We are not storing any other PII data*

>2) You are required to produce a Data Protection Impact Assessment (DPIA) for your
services, describing what kinds of PII data you will be collecting and for what purposes.
This will have to be updated as your services evolve.

*We are not storing any PII, but should create a DPIA to assert that.*

>3) To collect only as much information as required to process the user’s request and to
securely dispose of it when no longer required.

*We are not collecting any information from the user.*

>4) If you want to retain information for longer than 1 year, you must produce a Data
Retention Plan that indicates how long you plan to keep the pieces of PII data you have
collected and why you need to keep them that long.

*No PII stored, therefore no data retention rules apply.*

>5) To take reasonable security precautions to prevent unauthorized access, and to notify
the Eclipse Foundation (via privacy@eclipse.org ) immediately if you suspect a security
breach of any kind. Be sure to include the nature and scope of the suspected breach.

*We would agree to this*

>6) To ensure explicit consent has been given by the user before you start using cookies.
This requirement also includes cookies used by 3rd party services such as, but not
limited to: Google Tag Manager, and social media widgets.

*The following code is already implemented (provided by Eclipse), which means that the cookie consent pop up appears before any 3rd party services are invoked. The only widget we use is twitter web intent from the what's new page*
```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5WLCZXC');</script>
```

>7) Google Analytics is the only approved tool for collecting user data. Use of any other tool
for collecting user data requires the explicit consent of the Eclipse Foundation, which can
be sought by sending a request to privacy@eclipse.org. To use use Google Analytics,
you must ensure:
a) All committers on a project must have access to the data collected for that project
upon request
Eclipse Foundation Hosted Services Privacy and Acceptable Usage Policy v1.0 - October 18, 2018
b) Eclipse Webmaster (webmaster@eclipse-foundation.org) must be an
administrator on all Google Analytics properties
c) The Eclipse Foundation has right to audit the use of Google analytics and the
data collected, and the project must support the Eclipse Foundation in performing
the audit and adjust their analytical tooling if required
d) A user must be requested to give their consent, and explicit consent must be
given by the user before data is collected regarding that user
e) Google Analytics IP Anonymization feature must be turned on
f) Projects must ensure that they are not transmitting PII to Google Analytics
g) Projects must accept and follow Google Analytics Terms of Service

*We would ensure we meet these criteria and would not use any other data collections tools.*

>8) To make the contents of any virtual server available for auditing by Webmaster should
the need arise, and to provide support as required in order to carry out the audit process.

*We would agree to this*

>9) To ensure all web pages related to operation of the server use either the standard
Eclipse.org footer template, or a footer that prominently contains a copyright notice, and
the following set of links:
1) Main Eclipse Foundation website (https://www.eclipse.org)
2) Privacy policy (https://www.eclipse.org/legal/privacy.php)
3) Website terms of use (https://www.eclipse.org/legal/termsofuse.php)
4) Copyright agent (https://www.eclipse.org/legal/copyright.php)
5) Legal

*We already comply*

**Comment by SueChaplain** [comment]
@mstoodle @DanHeidinga @pshipton

Re-enabling Google Analytics is in our interests as it should allow us to make data-driven decisions based on how users interact with the website and user docs. Please can you review the process from Eclipse and +1 or -1 to proceed based on my answers.

**Comment by mstoodle** [comment]
I agree o the answers given in principle, but I would like to be shown what we are collecting so that I can agree we're not doing anything that goes against our answers.

**Comment by pshipton** [comment]
+1

Related to Mark's response, @SueChaplain do you have any older Google Analytics data, or has it all been purged? Do you have any similar Google Analytics data from another source?

**Comment by SueChaplain** [comment]
Think I'll have to set up a new dummy site to gather some data that we can look at (with IP anonymization). We were obliged to purge everything we had when GDPR was coming in .. across all the sites where we had it running. Even if we had that data, it would have contained IP addresses, so would be difficult to assess.

**Comment by pshipton** [comment]
> We were obliged to purge everything we had when GDPR was coming in .. across all the sites where we had it running.

It was a trick question, good answer. :)

**Comment by SueChaplain** [comment]
Re-visiting this issue, because we would really like to be gathering some analytics on website usage. Proving that we don't collect PI is tricky, because we have to turn GA back on and turning it on requires us to complete the Eclipse assessment. I did start to look at setting up some dummy sites with and without IP anonymization, but didn't get very far. 

Stepping back from this, I've taken a different approach based on Google documentation:

1. Article on IP anonymization in Google Analytics: https://support.google.com/analytics/answer/2763052?hl=en

>The IP anonymization feature in Analytics sets the last octet of IPv4 user IP addresses and the last 80 bits of IPv6 addresses to zeros in memory shortly after being sent to the Analytics Collection Network. The full IP address is never written to disk in this case. 

So, with IP anonymization on, we are not collecting IP address, which was Eclipse's primary concern.

2. Article on best practices to avoid sending PII in Google Analytics data: https://support.google.com/analytics/answer/6366371?hl=en&ref_topic=2919631

> **User IDs:**  we don't create userids for users, therefore no risk.
> **Page URLs and titles:**  we don't pass any PII as part of a page URL, therefore no risk. 
> **PII entered by users:**  we don't have any forms where users might enter PII, therefore no risk. We do have a search box where users might accidentally add PII but my understanding is that we'd have to create an event for it in GA to be able to collect information on search terms (see https://support.google.com/analytics/answer/1012264?hl=en). 
> **Data Import:**  we don't import any data, therefore no risk
> **Analytics features and privacy risk:**  we are not  using any of the Analytics features that might cause PII to be collected, therefore no risk.
> **Geolocation:**  we do not collect geolocation info that is GPS or fine-grained enough to identify an area less than 1 sq mile (e.g. a UK postal code), therefore no risk.
> **AdSense:**  we do not use AdSense, therefore no risk
> **Hashed and salted PII:**  there is no PII we want to collect so have no need for encrypted content, therefore no risk			- 
> **HIPAA Disclaimer:**  as we are not a Health Insurance Portability and Accountability Act associate, this does not apply.

3. Other considerations: 

Use of Widgets: We use twitter web intent to encourage readers to tweet the latest news about our releases directly from the What's new page. 

From https://developer.twitter.com/en/docs/twitter-for-websites/privacy.html

>You may choose whether Twitter widgets on your site help to tailor content and suggestions for Twitter users. You can opt out of having information from your website used for personalization by following the instructions below.

>Include the following snippet within the <meta> and <link> elements on your pages that include Twitter for Websites widgets: <meta name="twitter:dnt" content="on">

This meta data is present on the What's New page.

<hr>
Therefore, to the best of my knowledge, I think there are no GDPR risks to turn Google Analytics back on, with IP anonymization enabled.

@mstoodle @DanHeidinga @pshipton 
Please vote:

1. We enable GA, following the Eclipse process, with no further changes.
2. We disable web intents and enable GA, following the Eclipse process.
3. We drop the idea of gathering data to help us understand site usage, and I close this issue (which would be a shame) ;-)

I suppose there is a (4) - someone else validates my assessment.

**Comment by mstoodle** [comment]
Thanks for your diligence here, Sue. I'll vote for 1.

**Comment by DanHeidinga** [comment]
+ 1 to option 1 as well.

**Comment by pshipton** [comment]
Option 1 is fine with me.

**Comment by SueChaplain** [comment]
https://github.com/eclipse/openj9-website/pull/198

Eclipse web master has admin access to the Google Analytics account and data, as have project leads.

IP anonymization is turned on.
Twitter web intent turned off until we can implement cookie checking.
