### ISSUE TITLE
Broken link for 0.12.1 release notes

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9-website#158]
The link to the release notes on [this page](https://www.eclipse.org/openj9/docs/version0.12.1/) is broken.

The problem appears to be a missing dot near the end of the URL:

Current URL:
`https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.12/0.12.1md`

Correct URL:
`https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.12/0.12.1.md`

**Comment by zli1** [comment]
> The link to the release notes on [this page](https://www.eclipse.org/openj9/docs/version0.12.1/) is broken.
> 
> The problem appears to be a missing dot near the end of the URL:
> 
> Current URL:
> `https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.12/0.12.1md`
> 
> Correct URL:
> `https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.12/0.12.1.md`

The source of doc page (https://www.eclipse.org/openj9/docs/version0.12.1/) is located in the project openj9-docs(https://github.com/eclipse/openj9-docs). This issue shouldn't be target to this project.

**Comment by SueChaplain** [comment]
Fixing in https://github.com/eclipse/openj9-docs/pull/230
