### ISSUE TITLE
Create a common dockerhub repo

### ISSUE THREAD

**Issue by dsouzai** [eclipse/openj9-website#171]
Disclaimer: this is not directly related to website contents, but other blog related items have been captured here in past.

It would be nice if we had a common repo on dockerhub to put up images for experiments that people blog about (eg https://blog.openj9.org/2019/04/01/a-simple-jitaas-demo-on-docker-containers/).

**Comment by AdamBrousseau** [comment]
FYI we have permissions to push to the eclipse repo on DockerHub. We push our Jenkins slave images there for the build farm as well as the Docs image we use to build the Website Docs.

**Comment by SueChaplain** [comment]
Doing some new year hoovering ...... @dsouzai, I think this probably was missplaced here in the website repo as it has gone unassigned as far as I am aware. Do you know if work was done to create a folder at Docker Hub  ... I don't see anything. If not, is this still required?

**Comment by dsouzai** [comment]
It wasn't misplaced, @smlambert asked me to open it here. The reason behind it was to have a place where people who were writing blogs or whatever could put up docker images. However, I don't think there's really been any demand for it.

**Comment by SueChaplain** [comment]
OK. I'll leave it a while until @smlambert has had a chance to look at the issue. If there is no demand, we will then close.

**Comment by smlambert** [comment]
Apologies, I did not see this one, but do recall requesting it here.  While the change doesn't relate to this repo, I just wanted a record of what we decided to do.  

Given @AdamBrousseau 's note https://github.com/eclipse/openj9-website/issues/171#issuecomment-546370749, I think it would be good to use the eclipse repo on Dockerhub with a section for images supporting openj9 blog content.  Perhaps we can put a few of the additional details of how this can be done in this issue before closing it.  That way we can link to it when directing blog authors on how to proceed.

**Comment by AdamBrousseau** [comment]
DckerHub details

Eclipse has given our bot account write access to the [Eclipse org](https://hub.docker.com/u/eclipse) on DockerHub. This allows us to push our Jenkins agent images as well as our Doc build images. There is Jenkins build automation setup for those 2 builds. The password is stored in Jenkins credentials manager as well as in the encrypted secrets repository. Note there is no structure in an org so all the images are stored al the same top level (eg. https://hub.docker.com/r/eclipse/openj9-jenkins-agent-x86-ubuntu16).

In my opinion, given the demand, if a user would like to add an image using this account they should reach out to an infra member to have us push it to DocerHub for them.

**Comment by SueChaplain** [comment]
Closing this item. Requests should refer to Adams recommendation: 

>In my opinion, given the demand, if a user would like to add an image using this account they should reach out to an infra member to have us push it to DocerHub for them.
