### ISSUE TITLE
Incorrect Xdump doc for CEEDUMPs and dsn option

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9-website#179]
There's a problem with the following paragraph on [this page](https://www.eclipse.org/openj9/docs/xdump/):

> When producing system dump files **or CEEDUMPs** on z/OS platforms, use the dsn option instead of the file option. For example:
> 
> `java -Xdump:system:events=vmstop,dsn=%uid.MYDUMP`

The `dsn` option actually has no effect at all on the name of CEEDUMPs. As far as I'm aware there is no JVM option which allows you to specify the name of the CEEDUMP.

See https://github.com/eclipse/openj9/issues/6253#issuecomment-530508816 for more info.

**Comment by SueChaplain** [comment]
The `dsn` option is mentioned 3 times in the -Xdump topic. @pshipton - should we remove all references to it?

**Comment by paulcheeseman** [comment]
The `dsn` option works for system dumps, just not CEEDUMPs. So the reference to CEEDUMPs in this context should be removed.

> When producing system dump files ~or CEEDUMPs~ on z/OS platforms, use the dsn option instead of the file option. For example:
>
> `java -Xdump:system:events=vmstop,dsn=%uid.MYDUMP`


> This VM action does not apply to ~CEEDUMPs~ **system dumps** on z/OS operating systems that use the dsn option.
