### ISSUE TITLE
Add links to existing performance articles, blogs and slides

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#18]
Series of 3 articles. Add into the learn more section where we talk about performance
Post 1 links them all together:
https://developer.ibm.com/javasdk/2017/02/09/j9-jvm-architecture-basics-compiler-tuning/

**Comment by SueChaplain** [comment]
Vijay and Marius have provided some good charts for the website, which we will integrate into the learn more section. To cover the older article from Vijay and collect together some other useful resources, we plan to create a new FAQ

Q: **Where can I learn more about OpenJ9?**
A: The following recent articles, blog posts, and slides contain useful information about Eclipse OpenJ9. Note: You will find some references to IBM J9 where content was published before IBM contributed the JVM to the Eclipse Foundation.

-  [J9 JVM architecture basics and the JIT compiler](https://developer.ibm.com/javasdk/2017/02/09/j9-jvm-architecture-basics-compiler-tuning/)
- [Memory management, garbage collection (GC) policies, and GC diagnostic tools](https://developer.ibm.com/javasdk/2017/02/16/memory-spaces-garbage-collection/)
- [Java concurrency and locking](https://developer.ibm.com/javasdk/2017/02/23/java-concurrency-locking/)
- [J9: Under the hood of the next open source JVM](https://www.slideshare.net/DanHeidinga/j9-under-the-hood-of-the-next-open-source-jvm)
- [Reducing Garbage Collection pause times with Concurrent Scavenge and the Guarded Storage Facility](https://developer.ibm.com/javasdk/2017/09/18/reducing-garbage-collection-pause-times-concurrent-scavenge-guarded-storage-facility/)
- [How Concurrent Scavenge using the Guarded Storage Facility Works](https://developer.ibm.com/javasdk/2017/09/25/concurrent-scavenge-using-guarded-storage-facility-works/)
- [Are you still paying for unused memory when your Java app is idle?](https://developer.ibm.com/javasdk/2017/09/25/still-paying-unused-memory-java-app-idle/)

**Comment by mstoodle** [comment]
I will selfishly add [Under the hood of the Testarossa JIT Compiler](https://www.slideshare.net/MarkStoodley/under-the-hood-of-the-testarossa-jit-compiler)

**Comment by DanHeidinga** [comment]
+1 to @mstoodle's presentation.  It's a great into the JIT!

**Comment by pmhayward** [comment]
New "Resources" page added to OpenJ9 website

**Comment by DanHeidinga** [comment]
@pmhayward Can you link to the page from this issue?  Thanks

**Comment by pmhayward** [comment]
Apologies - wasn't live when I closed the issue!
https://www.eclipse.org/openj9/oj9_resources.html
