### ISSUE TITLE
About page content development

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#186]
![OpenJ9 V3](https://user-images.githubusercontent.com/18395037/66750291-01838100-ee84-11e9-8731-754ec0838c91.jpg)

Current FAQ. Mark those we want might want to keep with a check mark. These could be re-written into parts of the About page

- [ ] Is Eclipse OpenJ9 a replacement for OpenJDK? *people understand this better now*
- [x] Is Eclipse OpenJ9 the same as Hotspot? *we probably need to state the answer from this in*
- [x] What does the J9 in OpenJ9 stand for? *nice About reference*
- [ ] Why use Eclipse OpenJ9 instead of the default JVM? *don't need this - we have headliners*
- [ ] What license is Eclipse OpenJ9 made available under? *people know where to find this*
- [ ] Which OpenJDK versions and which platforms is Eclipse OpenJ9 supported on? *Find at Adopt*
- [x] How easy is it to migrate to OpenJDK with Eclipse OpenJ9? *We should have something and link*
- [ ] How can I discuss ideas and provide feedback to this community? *no - slack is on the home page*
- [x] Why did IBM contribute their J9 virtual machine to the Eclipse Foundation? *useful about*
- [ ] Why do I clone from https://github.com/ibmruntimes/openj9-openjdk-jdk8? *noone ever asked*
- [ ] I think I've found a performance issue. How can I be sure? *not needed*
- [ ] Where can I learn more about OpenJ9? *no - we'll have resources on the About page*

New design does not include a resources page. Instead, key resources could be added to the About page or moved elsewhere and linked to.

**Comment by SueChaplain** [comment]
From Peter H:

These are the 4 FAQs currently selected above. WIP re rewriting!...

**Is Eclipse OpenJ9 the same as Hotspot?***

Hotspot and Eclipse OpenJ9 are both Java virtual machines that can be included in an OpenJDK build, but each has different capabilities. Depending on the build process you follow, you can build an OpenJDK binary that includes either Eclipse OpenJ9 or Hotspot.

**What does the J9 in OpenJ9 stand for?**

To clear up a common misconception, J9 does *not* mean "Java 9". If you are interested in hearing about how J9 got its name, read this [blog post](https://medium.com/@rservant/how-did-the-j9-in-openj9-get-its-name-95a6416b4cb9).

**How easy is it to migrate to OpenJDK with Eclipse OpenJ9?**

Most Java applications should run without changing anything. However, if you are using a runtime environment that embeds the HotSpot VM and you set a lot of command-line options when you startyour Java application, read [New to OpenJ9?](https://www.eclipse.org/openj9/docs/openj9_newuser/) in the OpenJ9 docs. You might also find the article [Moving to OpenJ9](https://blog.openj9.org/2019/02/26/moving-to-openjdk-with-eclipse-openj9/) useful.

**Why did IBM contribute their J9 virtual machine to the Eclipse Foundation?**

IBM is publicly committed to bringing innovation into the open source development community. Contributing the J9 virtual machine, which has been at the core of IBM SDK, Java Technology Edition for many years, demonstrates that commitment. The OpenJ9 virtual machine is itself based on core technology components of the Eclipse OMR project, which was contributed by IBM to the Eclipse Foundation in 2016. IBM continues to invest resources in both Eclipse OpenJ9 and Eclipse OMR to ensure that their enterprise products can take advantage of the latest hardware technologies.

**Comment by SueChaplain** [comment]
Relevant rules for the display of company logos (Eclipse handbook):

**Company Logos**

Company logos may optionally be included on a project website, but only if the following conditions are met.

- The company is a member of the Eclipse Foundation;
- At least one project committer is an employee of the company in question; and
- The committer is active (i.e. they have made at least one commit in the last three months)

**Comment by SueChaplain** [comment]
Status on redesign:

- our history complete
- our future: awaiting outline content from project leads

**Comment by pmhayward** [comment]
Website redesign completed.
