### ISSUE TITLE
News page design

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#190]
News page:

- News reel for project releases
- Upcoming events
- Latest blogs

![OpenJ9 What's New](https://user-images.githubusercontent.com/18395037/66747542-bc0f8580-ee7c-11e9-850c-c0ae2e217bbc.jpg)

NOTES: 

- Banner like event message at top. This banner should be planned to start and stop on specific days so that it’s always showing users important information.
- New Release Info button takes you to the OpenJ9 user doc release topic.
- Hovering over an event should provide more detail
- Calendar should take people to the OpenJ9 gmail google calendar, which someone will have to maintain for events.
- Last 2 blogs are fed from the OpenJ9 blog site (https://blog.openj9.org/)
- See all blogs button takes you to the OpenJ9 blog site
- Header and footer design are in #156

**Comment by SamWillBeADevSomeday** [comment]
Hey there, i gave a visual update to the layout, header and footer.

![Contribution](https://user-images.githubusercontent.com/45536565/69478771-7b4d4980-0df6-11ea-89eb-651eca7839a6.png)
0
