### ISSUE TITLE
Docs site on mobile does not contain a TOC

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9-website#199]
Not sure if this issue belongs in this repo or openj9-docs.

On the [Docs site](https://www.eclipse.org/openj9/docs/), on a mobile device, the left menu or table of contents is not shown which makes it impossible to navigate the site. There is a "Hamburger" button, similar to the main site, but it's not clickable. Even when I request "Desktop site" and change to landscape view it doesn't display.

Env:
Android 9
Chrome 77.0.3865.116
Firefox 68.2.0

![Screenshot_20191025-101800__01](https://user-images.githubusercontent.com/6430052/67578635-dcf39880-f710-11e9-9b03-325b38d3895f.jpg)

**Comment by DanHeidinga** [comment]
I have similar problems on my laptop with Safari which I mention as it might be worth rethinking how that hamburger menu works / is implementef

**Comment by SueChaplain** [comment]
>I have similar problems on my laptop with Safari which I mention as it might be worth rethinking how that hamburger menu works / is implementef

The hamburger is part of the default theme, which we do apply some change to. I think something must have got broken when we last updated our dependency levels. Problem is under investigation.

**Comment by SueChaplain** [comment]
This issue is moved to https://github.com/eclipse/openj9-docs/issues/420, where a fix is in progress. Closing this issue
