### ISSUE TITLE
Contribute on GitHub button link broken

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9-website#2]
The "Contribute on GitHub" orange button points to https://github.com/eclipse/openj9/contributing.md however this is not correct. "contributing" should be capitalized and is missing the branch blob. The correct link should be to https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md.

**Comment by SueChaplain** [comment]
Problem fixed. Please re-test.

**Comment by fjeremic** [comment]
Working as intended now.
