### ISSUE TITLE
Add default make target to configure step

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9-website#23]
Based on discussion [here](https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/34), I think there's a distinct usability improvement if we change the configure step recommendation to 

    bash ./configure --with-freemarker-jar=/root/freemarker.jar --with-default-make-target=images

as described by @keithc-ca [here](https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/34#issuecomment-333133415). The reason is the default `exploded-images` target doesn't work, so if you forget to type `make images`, you'll get a build break with no indication of why.

**Comment by SueChaplain** [comment]
Unfortunately the extra chars of the string cause the pre block to add a scroll bar
![issue23](https://user-images.githubusercontent.com/18395037/31024367-b6d4a000-a536-11e7-8176-dfab9d01f803.PNG)

I can push this as is, or this can wait a bit longer to fix CSS. Dan is also wanting a longer string for the raw dockerfiles, so I think we must do something to try and avoid the scrolls ... makes the site look ugly. Your preference? 

Push now, fix later ... or wait?

**Comment by mgaudet** [comment]
One option would be to escape the newlines:

```
bash ./configure --with-freemarker-jar=/root/freemarker.jar \
                 --with-default-make-target=images
```

I believe that should copy-paste fine.

**Comment by mgaudet** [comment]
I'll defer to others on the push-now-or-later issue. Not urgent IMO, but nice to have.

**Comment by mstoodle** [comment]
Does this have to be part of the minimal "here's how you can build OpenJDK with OpenJ9" experience? This feels like a very useful detail that could be provided on a "More details if you want to do more than just try out the build" page.

After all, our instructions do not say to just type make.

I guess the thing is: isn't this more of an OpenJDK configure detail than an OpenJ9 configure detail?

**Comment by mstoodle** [comment]
alternatively, could the default directions say "make images" rather than "make all" ?

**Comment by mgaudet** [comment]
It's 100% just a usability issue; Most tools default target is expected to work and 'do the right thing'; And, if your hands lead your eyes, and you type `make` rather than `make all` or `make images` (why is `exploded-images` not included in all, but the default 🤔 ) it fails in a way that points the finger directly at J9, leaving behind a terrible impression of quality.

IMO, `exploded-images` should work, or we should change the default target universally, but this is a very low impact way to ensure people get a good impression of the OpenJ9 build.

**Comment by SueChaplain** [comment]
@mgaudet  Can we agree to add something as part of issue #25 to cover this and close this item?

**Comment by SueChaplain** [comment]
Handled in #25 (https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V9.md)
Closing
