### ISSUE TITLE
Question about Search Engine Optimization

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/openj9-website#235]
I am wondering if anyone is looking at SEO for the OpenJ9 website.

I've heard from a couple of people that the website is not always showing up as the first result when they search on Google.

**Comment by SueChaplain** [comment]
We have a re-design underway @Leonardo2718 - we'll make sure we cover this aspect. Thanks

**Comment by SueChaplain** [comment]
Closing as SEO has been handled in the new website design, which we plan to roll out today.
