### ISSUE TITLE
Tabs on build instructions seem to be broken

### ISSUE THREAD

**Issue by youngar** [eclipse/openj9-website#238]
The tabs don't seem to do anything on the build page: https://www.eclipse.org/openj9/oj9_build.html. I would expect the tabs to cause different build instructions to appear below. Refreshing the page after clicking a tab seems to render the proper content.

Tested on:
Google Chrome 81.0.4044.43 (Official Build) beta (64-bit)
Firefox 73

**Comment by fjeremic** [comment]
On Firefox 73 I see all the tabs rendered on one page:

![image](https://user-images.githubusercontent.com/16259104/76363842-3b08cd00-62fa-11ea-9bc0-390cdcb44136.png)

Clicking on the tab links just scrolls the page down. If I refresh a few times sometimes it will render properly with proper tabs. Seems on and off. It's really weird.

**Comment by SueChaplain** [comment]
Investigating

**Comment by SueChaplain** [comment]
The issue seems to be with browsers that block javascript. We've laid the page out differently to get around this. https://github.com/eclipse/openj9-website/pull/241
