### ISSUE TITLE
Shared classes articles for the resources page

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-website#24]
The articles about shared classes can be added to the resources page of the web site - https://www.eclipse.org/openj9/oj9_resources.html

https://www.ibm.com/developerworks/java/library/j-ibmjava4/index.html

https://www.ibm.com/developerworks/java/library/j-sharedclasses/

**Comment by pmhayward** [comment]
Links now added to https://www.eclipse.org/openj9/oj9_resources.html
