### ISSUE TITLE
Dockerfiles are deleted

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-website#250]
The Dockerfile's referred to by https://www.eclipse.org/openj9/oj9_build.html are deleted and replaced by a script. See https://github.com/eclipse/openj9/pull/9371 and the instructions for using the script in https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md

The instructions for other versions will be updated shortly.

**Comment by pshipton** [comment]
@keithc-ca 

FYI the website is soon to be obsolete anyway, replaced by https://eclipse.github.io/openj9-website/ which doesn't contain build instructions.

**Comment by SueChaplain** [comment]
Closing as the build page does not feature on the new website, which we plan to roll out today.
