### ISSUE TITLE
Include the "50%" in the less memory text on the front page

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-website#27]
The front page has the following text "Low memory footprint".  We should highlight the 50% less footprint in that as it's eye catching.

page: https://www.eclipse.org/openj9/index.html
new text: "50% Lower memory footprint"

**Comment by SueChaplain** [comment]
@DanHeidinga Are you referring to the headlines?
"Low memory footprint. Fast startup time. High application throughput"
"50% less footprint. Fast startup time. High application throughput"

- I'm not sure we should put a "point in time" statement at that level. @vijaysun-omr ?

We do say " The memory footprint is around half the size of other JVM implementations." in Learn More. That was written before we had the actual performance data to back it up, so perhaps that could be a little more direct?

**Comment by DanHeidinga** [comment]
Yes, I was referring to the headlines.  That "50% less" number garnered a lot of attraction at JavaOne.  We want it to be prominent and obvious to visitors as it will help drive interest in the project.

**Comment by SueChaplain** [comment]
Dan. We talked about this. Consensus here was that we can't just say "50% less footprint" without saying what it is 50% less than. That rather messes up the 3 short impact statements:

"Low memory footprint. Fast startup time. High application throughput"

When you google Openj9 you get this:

_"Boost your Java application performance. Low memory footprint. Fast startup time. High application throughput. Optimized to run Java applications ..."_

If we start adding in more words ("50% less memory footprint than Hotspot"?), we won't get all the high impact messages in the search results. 

We have another open issue for breaking out a performance page. We could try to incorporate that "50%" claim as the headline there instead? (Although when I look at the graphs I see some showing 40% and some showing around 60% ..... which one are you looking at?)

**Comment by DanHeidinga** [comment]
The suggestion came out of conversations with the Eclipse Foundation board members at their booth during JavaOne.  The "50% less memory" is a much stronger impact statement than "Low memory footprint" and they suggested we should change the sentence to highlight the claim.

**Comment by DanHeidinga** [comment]
50% less is the general claim we've been using as a good general claim.  The Daytrader.md link highlights all the details so I'm not concerned with using 50% as a headline claim.

**Comment by vijaysun-omr** [comment]
I could go either way but am more in agreement with what @SueChaplain mentioned in that specific % numbers would be better on the performance page that we have an issue for.

**Comment by DanHeidinga** [comment]
Given the lack of interest in pursing this, closing now.

**Comment by SueChaplain** [comment]
@DanHeidinga - we are working on a new performance page and that will be up front on it!
