### ISSUE TITLE
The OpenJ9 community call invitation is out of date

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-website#287]
There is a "Join community calls" section on https://www.eclipse.org/openj9/ with an "Add to Calendar" link.
https://calendar.google.com/calendar?cid=YjBnYjB0ZzNxaTZhb3NhZGZnbG0wa3BjY29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

The meeting time is moved to Tues 10:30 - 11am ET. The calendar invite needs to be updated.
@SueChaplain fyi

**Comment by SueChaplain** [comment]
The link is a calendar share from the openj9.bot gmail account, which I had completely forgotten was set up! I've amended the meeting there. Clicking that link now should create a meeting on the correct day and time. It seems to work for me. Closing this issue.
