### ISSUE TITLE
Rename the "Why does my Java application perform worse with Eclipse OpenJ9?" FAQ question

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-website#29]
This question doesn't create a good impression for users looking at the FAQ for the first time.  The question should be renamed to provide a better first impression.

Proposed new title: "I think I've found a performance issue... How can I be sure?"

Hopefully this won't be a frequently asked question!

**Comment by SueChaplain** [comment]
@vijaysun-omr 
Adding Vijay for comment because this Q&A was provided by him.

**Comment by vijaysun-omr** [comment]
To be honest, I spent almost all my time on the "answer" to the question :) rather than the question itself. I'm fine with a different wording for the question @mstoodle ?

**Comment by pmhayward** [comment]
Title now changed as above
