### ISSUE TITLE
Preparation work for OpenJDK8

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#33]
To accommodate OpenJDK8 with OpenJ9 alongside OpenJDK9 with OpenJ9 (when available), we should  plan ahead for some changes to the website

**Index page:**
- acknowledge that you can do both
- Top build it button could stay the same, pointing to AdoptOpenJDK for variant=openjdk9-openj9 or variant=openjdk8-openj9, depending on which one we think will be most popular. 8?
- The build it button can be split into 2 halves, like Ask questions, to cover instructions for 8 and 9 separately.

**Build page:**
- duplicate the page for OpenJDK8 builds
- envisage some sort of tab at the top of each page that allows you to flip easily between OpenJDK8 and OpenJDK9 build instructions. The pages will be largely identical but reference different target repos (& dockerfiles?) I think this is cleaner than having to say "if you are building 8, run ....." etc.
- need to validate all build and test instuctions.

**FAQ:** 
- this should probably have a new question: Can I build an OpenJDK V8 with OpenJ9 as well as an OpenJDK9 with OpenJ9?

**Performance:**
- There is already a call for a performance page (issue #26). When we have one we can introduce performance results for 8 as well as 9 (as and when available).

@pmhayward  @doveye  and others. Please add any thoughts.

**Comment by mstoodle** [comment]
I think you may want to ask multiple questions: How can I build OpenJDK with OpenJ9 for Java 8? How can I build OpenJDK with OpenJ9 for Java 9?

...because there will be 18.3 and 18.9 ones coming "shortly" and we'll always have multiple versions we'll need to build against.

**Comment by SueChaplain** [comment]
Absolutely. We need a strategy that accommodates multiple options and hopefully the build process will be nigh on identical.

**Comment by SueChaplain** [comment]
Further thoughts on this @mstoodle is that the website should primarily support one LTS and one feature release. 

So right now we have OpenJDK 9
Next we integrate OpenJDK 8 (LTS) as the prime "go grab version"and OpenJDK 9 as the feature release.
Next we switch to OpenJDK 8 (LTS) as the prime "go grab version"and OpenJDK 18.3 ....
Next we switch to OpenJDK 18.9 (LTS) as the prime "go grab version"and OpenJDK 19.3(?) .....

We can still include information about finding other versions at AdoptOpenJDK, and we can still store build instructions for each version (ideally in eclipse/openj9/buildenv ...?)

**Comment by mstoodle** [comment]
we probably need to be able to support both Java 9 and Java 18.3 at the same time, I *think* . So maybe one LTS, and then current and next "feature" release ?

Developers and even some users will want and need to figure out how to work on 18.3 at the same time that 9 is the supported "feature" release (is that the official term for releases between LTS versions?).

**Comment by SueChaplain** [comment]
Fair point. We'll plan accordingly. Thanks!

**Comment by andrew-m-leonard** [comment]
Some potential difference of the build page from jdk9 to jdk8:
- There will be "jdk8" Dockerfile's
- Manual apt-get list will specify openjdk-7-jdk instead of openjdk-8-jdk
- This statement not relevant to JDK8 I believe "For Linux on other architectures, download the IBM SDK for Java 8 rather than the openjdk-8-jdk package. The IBM versions contain a JIT compiler that will significantly accelerate compile time."
- All "jdk9" references change to "jdk8"
