### ISSUE TITLE
intro-text1 formatting on oj9_resources page not centre aligned when browser window is wide

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9-website#36]
Page : https://www.eclipse.org/openj9/oj9_resources.html
Text:
>Follow the links to read recent articles, blog posts, and slides that contain useful information about OpenJ9.
Where can I learn more about Eclipse OpenJ9?

This text is aligned improperly for me when browser window is full monitor width (fine when narrower). The first line starts at ~centre and fills right and the second line starts ~left and fills to centre.
Tested on Chrome (61.0.3163.100) and FF (55.0.2) (OS Linux Mint 18.2)
100% zoom
Monitor resolution 1920 width

Full width :-1: :
![image](https://user-images.githubusercontent.com/6430052/31506845-a4821ef4-af46-11e7-9f7e-a15ec70b9090.png)
Less width :+1: :
![image](https://user-images.githubusercontent.com/6430052/31506864-acecb7ca-af46-11e7-90a0-945d10619255.png)

**Comment by AdamBrousseau** [comment]
Just noticed the line order changes too

**Comment by AdamBrousseau** [comment]
confirmed same behaviour on OSX/Safari

**Comment by SueChaplain** [comment]
Thanks @AdamBrousseau. We'll have a go at reproducing this here. All my attempts so far on Windows (FF, IE, Chrome) and Ubuntu (FF & Chrome) behave as expected, even at 300%. 

The line re-ordering is really odd ... how does that happen?!

**Comment by pmhayward** [comment]
I can reproduce the problem by stretching the browser window to about 1780px wide. 
Doubt it's browser/platform-specific, rather some combination of using css flex, multiple spans, and general ignorance on my part :)
Will investigate...
