### ISSUE TITLE
docker commands may need to be run with sudo

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9-website#4]
We may want to add a preamble to the two docker commands to remind people they may need to run those commands with "sudo" access.

You get a slightly cryptic error message (which is susceptible to googling, so it's probably not vital that we address it):
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Comment by SueChaplain** [comment]
Why would some people need to run as "sudo" and not others? What are you logged in as by default when you go through the build process? ROOT?

**Comment by mstoodle** [comment]
it depends on how you've configured your machine; see https://docs.docker.com/engine/reference/commandline/cli/#description . I don't think we should suck that in, we should link to it via some suggestive text like underneath the docker commands":
  (did you see "Cannot connect to the Docker daemon. Is the docker daemon running on this host"?)

Maybe we can rely on people googling the error message. I wouldn't like that page to get too cluttered (it's actually already too cluttered, in my opinion :) ).

**Comment by SueChaplain** [comment]
I guess it could just be one line, although added to my other comment for mapping a local directory, the section would grow a bit. If we had several trip up points we could point to "common build issues" instead, but I'm not sure we do (thankfully!) 

Example update in *italics*:

Save the Dockerfile to your current directory and specify these commands to build and run the Docker image:

> docker build -t openj9 -f Dockerfile .
> docker run -it openj9

*Depending on your [Docker system configuration](https://docs.docker.com/engine/reference/commandline/cli/#description), you might need to prefix these commands with `sudo`.*
Now that you have the Docker image running, you are ready to move to the next step.

**Comment by SueChaplain** [comment]
Website updated. Closing this issue.
