### ISSUE TITLE
Add Github stars rating to home page

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#43]
Discuss
![stars](https://user-images.githubusercontent.com/18395037/31779703-a8787c88-b4eb-11e7-83ad-0ec1dbac55a9.PNG)

 use of https://ghbtns.com/ to add stars (and watchers) to website.
Apache 2 licensed code.

@mstoodle - would you like to see this?

**Comment by mstoodle** [comment]
i suppose it's a relatively easy thing to add, but I don't really have a strong opinion about it either way.

we would have to fill out a CQ to use it, of course, but that's a very minor thing :) .

@DanHeidinga @pshipton @jonathanwoodford opinions?

**Comment by jonathanwoodford** [comment]
From my perspective, I can not see the strong user story for this, at this point in time.

We could have it as a low priority issue on our backlog.

**Comment by SueChaplain** [comment]
Closing. Re-open if/when it's worth working on.
