### ISSUE TITLE
Integrate the Docker test capability into the build page

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#47]
The work here should be integrated into the build page and the terminology should be updated for consistency:

https://github.com/eclipse/openj9/tree/master/buildenv/docker/test

**Comment by SueChaplain** [comment]
@smlambert 

Please can you let me know if the following section is appropriate to add to the "Test" section of the [OpenJ9 build page](https://www.eclipse.org/openj9/oj9_build.html). 

After the `-version` output you'll find the following sentence ...... my new part in **bold**

*You can also download and run some or all of these tests manually on your own machine.* 

**Running OpenJ9 tests requires a few extra tools and utilities. Our test [dockerfile](https://github.com/eclipse/openj9/blob/master/buildenv/docker/test/Dockerfile) extends the OpenJ9 dockerfile that you selected in "Prepare your system" to include these tools in an "OpenJ9 build and test" image. **

**Tip: Download the tests you want to run into a local directory. When you run your container, map the local directory to a directory in the container. For example:**

`docker run -it -v <local_directory>:/test openj9-buildandtest`

**Inside the container `openj9-buildandtest` you'll find the tests in the `/test` directory. To learn how to run tests, read the [Quick Start Guide](https://github.com/eclipse/openj9/blob/master/test/README.md).**

I'll also update and do a PR for https://github.com/eclipse/openj9/tree/master/buildenv/docker/test to get some consistency between pages.

**Comment by smlambert** [comment]
Here are a few minor updates:

after "a few extra tools and utilities."  the sentence:  

You can install these [prerequisites](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) on your own machine and follow the Quick Start Guide.    

Alternatively, our test dockerfile extends the OpenJ9 dockerfile that you selected in "Prepare your system" to include these tools in an "OpenJ9 build and test" image.  

Tip: If you wish to run the OpenJ9 functional tests, they live in the /test dir of the openj9 repository.  Clone the repository into a local directory.  When you run your container, map the local openj9/test directory to a directory in the container.  

Inside the container openj9-buildandtest you'll see the functional tests have been mapped to the /test directory.  ... 

I agree that the docker/test/README could use a rework, thanks for helping with it 👍

**Comment by SueChaplain** [comment]
Thanks @smlambert -  If someone has used the Dockerfile to build a binary first, I guess they already have all the functional tests from the clone in ./get_source.sh? 

If so, should I make the tip about the system tests? Where do they live?

**Comment by smlambert** [comment]
Yes, we need to update the openj9 test readme to better describe or at least reference all of the other testing that can be applied to openj9 builds that we [run at AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/README.md).  Test material lives all over the place (different system tests live at Adopt and OpenJ9 repos) 

You can "git clone https://github.com/AdoptOpenJDK/openjdk-tests.git", overlay system/openjdk/external/perf/jck directories alongside the functional directory and [run them](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/userGuide.md#clone-the-repo-and-pick-up-the-dependencies) also (though in the cases of perf and jck, you may need a license to do so, if you have no local test material / no license, those tests will be skipped).

**Comment by SueChaplain** [comment]
Thanks @smlambert  - I've chosen to keep the section as simple as possible and not include the tip. I think it is better that we put the complexity of the testing into markdown in the openj9 repo docker/test/readme.  If you see an obvious omission on the build page for test, please raise a new issue. Otherwise happy to work with you and the team to improve the docker/test/readme content.
