### ISSUE TITLE
What's New should have direct links

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9-website#51]
It would be nice if the content of What's New had direct links, so that as the page evolves, we don't lose the ability to link to things like the OpenJDK8 announcement.

**Comment by SueChaplain** [comment]
I did put an ID in .....

https://www.eclipse.org/openj9/oj9_whatsnew.html#openjdk8

Is that what you meant?

**Comment by mgaudet** [comment]
That's a good one. I had sort of been thinking 1-page per story. But that could suffice for now.
