### ISSUE TITLE
Update image directories detailed on the build page

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#56]
The following section:
------------------------------------
Two Java builds are produced: a full developer kit (jdk) and a runtime environment (jre):

- build/&lt;platform>/images/jdk
- build/&lt;platform>/images/jre
------------------------------------

The directory names have been changed to: 

- build/&lt;platform>/images/j2sdk-image
- build/&lt;platform>/images/j2re-image

Detailed build instructions also need checking.

**Comment by pshipton** [comment]
Note jdk and jre are correct for Java 9 and later. Java 8 uses j2sdk-image and j2re-image
