### ISSUE TITLE
Build page JDK version unclear

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9-website#58]
On the top-left of the OpenJDK on Openj9 build page ([link](https://www.eclipse.org/openj9/oj9_build.html), for unambiguity), there are a pair of buttons to switch between jdk9 and jdk8. The selected JDK is a dull blue with minimal text, and the unselected JDK is a vivid orange with more verbose text. This keeps tripping me up, though simply changing the colors might not solve the problem for everyone (as different cultures = different colour significance).

I recommend adding an arrow next to the selected Java version; clearly separate from the button.

E.g.

(JDK 8)
(JDK 9)  <<

Any thoughts, on the problem or the proposed solution?

**Comment by SueChaplain** [comment]
Thanks @adamfarley for your comments and suggestions. We've had similar feedback from other people, so opening an issue is definitely a timely thing to do.

The colours are logical (all links are orange, hence you when you click on an orange "Build X" you are going somewhere else), but not logical enough as this has phased lots of people so we need to re-think! 

The chevrons might be a good solution. Other suggestions have been around changing the text on the buttons to say "go to ...".  Let's give it a few days to see what suggestions come in and we can then try to implement something better.

**Comment by adamfarley** [comment]
That sounds reasonable.
