### ISSUE TITLE
Advertise our regular hangouts on the website

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#59]
- create a What's new section telling people about the regular hangouts and how to find out when they take place.
- create an FAQ "How can I discuss ideas and provide feedback to this community?" (There's more than one answer, but we'll get the hangouts in the list"
- update the "Get involved" section on the home page to mention regular hangouts

**Comment by SueChaplain** [comment]
*What's new draft - please feel free to comment / make suggestions*

**Come "hangout" with the OpenJ9 community**

&lt;date> 

Our regular community hangouts are a great place to meet the team and find out what is going on in the OpenJ9 project. Everyone is welcome and the agenda is pretty flexible. Generally we discuss hot topics like release plans, issues, ideas, and working processes, but we're open to requests.  If you'd like to get involved at some level, why not come along? Maybe you have some suggestions, or maybe you'd like to provide some feedback about your experiences using an OpenJDK with OpenJ9. If you just want to come and listen, well that's fine too! 

Schedules, agendas, minutes, and recordings are posted in the [OpenJ9 slack channel](https://openj9.slack.com/messages/C8312LCV9/). 
To join the channel: [request an invitation](https://www.eclipse.org/openj9/oj9_joinslack.html).

**Comment by SueChaplain** [comment]
*FAQ draft - please feel free to comment / make suggestions*

**How can I discuss ideas and provide feedback to this community?**

There are a number of ways that you can engage with the OpenJ9 community:

- Join our [OpenJ9 slack channel](https://openj9.slack.com/messages/C8312LCV9/) where you can collaborate directly with developers and other contributors on the project. To join the channel, [request an invitation](https://www.eclipse.org/openj9/oj9_joinslack.html).
- Join the [Eclipse mailing list](https://dev.eclipse.org/mailman/listinfo/openj9-dev) and post a message to our development community.
- Come along to our regular hangouts, where you can speak to OpenJ9 developers directly, ask questions, and share your experiences.  Schedules and agendas for hangouts are posted in the OpenJ9 slack channel.
- Create an issue in our [OpenJ9 GitHub repository](https://github.com/eclipse/openj9/issues).

**Comment by SueChaplain** [comment]
*Get involved draft update - feel free to comment/make suggestions*

**Home page - "Contribute" section**

If you are interested in contributing to the development of this open-source project, check out the contribution guide in our GitHub repository. If you want to find out more about how we work, why not come along to a *meetup*(linking to the what's new item). You can also find out more about the project, including release plans, at our Eclipse Foundation project page.

**Comment by SueChaplain** [comment]
@mstoodle  @DanHeidinga @pshipton @jonathanwoodford
Please review proposed changes to the website to advertise the hangouts.

**Comment by mstoodle** [comment]
All looks great to me, @SueChaplain !

Maybe you could also add the OpenJ9 twitter account to the list of ways to engage ... currently a "low volume" information source :) .

**Comment by DanHeidinga** [comment]
This looks good!  Thanks @SueChaplain

**Comment by pshipton** [comment]
> Schedules and agendas for hangouts are posted in the OpenJ9 slack channel.

Schedules and agendas for hangouts are posted in the OpenJ9 slack workspace, in the #planning channel.

**Comment by SueChaplain** [comment]
@pshipton I agree that the terminology we use around slack is not quite right. It is a workspace and we should probably refer to either "OpenJ9 slack workspace" or "OpenJ9 slack channel**s**" throughout. I'll fix up as I go.

**Comment by SueChaplain** [comment]
Create a public calendar for the hangout and integrate into the website.

Public calendar: https://calendar.google.com/calendar?cid=YjBnYjB0ZzNxaTZhb3NhZGZnbG0wa3BjY29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
