### ISSUE TITLE
Preparation for v0.8 release

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#62]
Things to do:

- Create a what's new section 
- Home page: Point the "download now" buttons at the 8 builds instead of 9 (#53), point the read the docs to IBM KC version 8 VM reference (https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_intro.html)

@DanHeidinga @mstoodle @pshipton Anything else you'd like to see happen here for the website?

**Comment by SueChaplain** [comment]
Staged: http://staging.eclipse.org/openj9/oj9_whatsnew.html

URL for tweets / direct access to what's new section is :
http://staging.eclipse.org/openj9/oj9_whatsnew.html#v0.8

**Comment by pshipton** [comment]
This link requests an Eclipse password. I wasn't able to access it.
