### ISSUE TITLE
Add links to external articles and experiences people have with using OpenJ9

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#67]
As suggested by @mstoodle in todays hangout, we should find some way of adding links to articles and blogs that are created outside of the project. 

Mark can you add links to the articles you were referring to please?

**Comment by mstoodle** [comment]
There were two specifically I found this week with random googling:

1. http://psamolysov.blogspot.ca/2018/02/how-to-build-openj9-jdk-from-sources-docker-ansible.html

2. https://medium.com/criciumadev/using-openj9-for-running-microservices-in-docker-ebb0b5da1e00

**Comment by mstoodle** [comment]
Having a nice obvious way for people to tell us about a new article would be good too. Maybe a big button that opens a new issue at this repo (https://github.com/eclipse/openj9-website/issues/new), especially if it fills in some title text automatically so the person just has to paste their link and save it? (just an idea :) )

**Comment by DanHeidinga** [comment]
And also https://www.infoq.com/news/2018/03/OMR-OpenJ9

**Comment by SueChaplain** [comment]
And another found by @andrewcraik 
https://dzone.com/articles/hello-openj9-on-windows-i-didnt-expect-you-so-soon
Thanks Andrew!
