### ISSUE TITLE
Discussion: Wordpress vs website "What's new" page for blogs

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#68]
Back in November we rustled up a What's new page to capture project news, events, milestones etc for the project. As items were added, we restyled the page to look more like a blog, and (not yet contributed) we have integrated twitter so that each item can be tweeted for the  users twitter account ( and they get offered an invitation to follow the OpenJ9 twitter account). However, the page is not Wordpress, it is pure HTML, and any blogs or articles have to be added in as HTML.

On today's "Ask the OpenJ9 community" call there was some discussion about how easy it is, or isn't, to add a blog. Anyone can do it by forking the repo, making changes to the whatsnew.html file and issuing a PR for a committer to merge. You can also test your changes on a staging server at Eclipse. But it isn't Wordpress and doesn't have the built in features that come with Wordpress. 

So, I'm opening up this discussion to see what people think about having a Wordpress site that we can link to from the Eclipse OpenJ9 website ... and which we can try to "style" to make it look like an integral part of the site. There are advantages and disadvantages. It will be easier for people to create articles and blogs independently and we can take advantage of some of the built in Wordpress features. However, if we want a custom domain name or Google Analytics, you don't get those on the free plan.

**Comment by DanHeidinga** [comment]
I think blogs and what's new serve different purposes.  What's new should be highlighting new features and changes in the OpenJ9 - announcements basically.  Blogs can be broader, explaining existing features, build instructions, connections to other projects, etc and support longer content.  

We probably want both whatsnew.html and a new eclipse.org/openj9/blog.

I don't have a strong opinion on whether the blog is Wordpress or something else.  See https://github.com/mstoodle/mstoodle.github.io for an example of "something else".

**Comment by smlambert** [comment]
And here is the example of the Adopt blog: https://blog.adoptopenjdk.net/

Attached a picture of how its integrated into the website
![adoptblogsidebar](https://user-images.githubusercontent.com/2836948/37480018-80f5474a-2854-11e8-83a2-5392ab482e37.jpg)

**Comment by SueChaplain** [comment]
@smlambert I took a look at Adopts blog yesterday. I was looking at whether we could do the same - the website integration is a simple link. They are on Wordpress and must be on a paid-for plan because they can use a custom domain name. I'm not sure we have money for it so we'd end up with something like openj9.wordpress.com as our site name. The bigger problem, I think, by not having a paid-for plan is the ability to use Google Analytics. If we're writing bigger articles we're going to want to know how well they are being received.

@DanHeidinga - I agree that what we have doesn't entirely suit our purposes. I was half thinking about morphing the What's new page into more of a blog. We use the JavaSDK developer center to announce "What's new" as well as publish articles, and that seems to work ok for mixing these types of things together. If we don't want to do that, we can look at something else.

We could have another GitHub repo serving a Jekyll instance like Mark's just for blogs. Would people find Jekyll any easier to work with than our current website? If so, we can create something that blends with the website and link it in the way that Adopt do. It would be another "resource" to manage though. Perhaps finding an easier method for people to contribute to the current website is preferable and then setting up a blog area on that site. 

Thoughts?

**Comment by smlambert** [comment]
I will ask about the paid plan, we should have a small marketing budget we can dip into, and this is most certainly a worthy cause as it means an easy avenue to sharing interesting ideas, tutorials, announcements and so forth.

**Comment by DanHeidinga** [comment]
I don't have enough experience with either Jekyll or Wordpress to know which is better.  My main concerns are having something that, as you said, suits our purposes better.  Something easy to add text and images to.  

Another option might be to reach out to the Eclipse Foundation and see if there's an existing paid account we can extend or marketing funds (via Friends of Eclipse) our project can tap into.

**Comment by pshipton** [comment]
It might come down to what the people who are going to maintain the site are used to. @smlambert mentioned a few things at the community meeting today that would make Wordpress a good choice: easy to use, accounts for all the committers, a review process...

**Comment by SueChaplain** [comment]
I wasn't able to attend the community meeting yesterday, but I do agree with @smlambert - Wordpress is a good solution and something a lot of us are familiar with. I looked to see whether other Eclipse projects are using it ... there are some on wordpress.com. If we set up there it would be good to go for a paid option to get Google Analytics. Without it we won't know what type of articles are interesting to people. It would need more looking into though as the .com site limits what you can do on the lower paid options.

The other approach is to use wordpress.org and host it somewhere. AdoptOpenJDK are using Wordpress hosted on Hostinger (cheap site but still looks to be ~£8/mth  although there is a deal on at the moment to get it for £3/mth for the next 2 years). 

Jekyll is free, hosted on GitHub ..... but will require users to be a bit savvy about making contributions.

**Comment by DanHeidinga** [comment]
@SueChaplain @smlambert I'm not familiar with Wordpress and the pros / cons of the hosting at Wordpress or self hosting.  Can you (or others familiar) with the options put together a proposal that outlines the options, the costs, and what we get for that money?

I can take that forward and see if we can get funding internally to support this for OpenJ9.

**Comment by smlambert** [comment]
I am also willing to just buy us 2 years at the deal price to avoid spending the time to pull together a proposal.  ;)

**Comment by pshipton** [comment]
https://wordpress.com/#plans That's US$33 a month for the business plan with Google Analytics Integration

**Comment by SueChaplain** [comment]
https://www.hostinger.co.uk/cart/

12 month plan special offer, including taxes:  £46.08 with openj9.net domain name thrown in. 4 days left on the offer. That would mean hosting our own wordpress.org with max flexibility on plugins/customisation.

**Comment by llxia** [comment]
Wordpress     


From what I have heard, wordpress can be painful to maintain. whereas

**Comment by llxia** [comment]
From what I have heard, Wordpress can be painful to maintain. i.e., Wordpress update is live. If something goes wrong, the site is down and it hard to roll back and figure out why. Wordpress stores data in database whereas Jekyll uses static page stored in git. We can have more control by using git. For just text and image, Wordpress maybe overkill. But I agree, it seems you have to be a bit savvy to make contributions in Jekyll.

**Comment by smlambert** [comment]
Sounds like need to step through the user story of "I want to edit/publish a blog post"...  and judge how they compare.  As Jekyll equates to pull requests, which everyone is already used to, so likely not a blocker.  It may be more a matter of simply agreeing on themes and process.

**Comment by SueChaplain** [comment]
@smlambert We already have a google analytics seed. We set it up for the OpenJ9 website and you can use it in multiple places to get all the data back to one dashboard. It's just a case of including a short section in each page on the site.

**Comment by smlambert** [comment]
Perfect (re: seed), and what the link I shared describe is how Jekyll has a convenience feature of trickling down the reference (so you do not need to edit each page), but rather you include an analytics.html page and it will be included in all your pages automatically.

I will play with Jekyll as its seems like lots of good parts (and based on @llxia comments about maintenance story, jekyll's git integration makes sense as it will be savvy developers writing blog posts and sharing technical ideas), with plan to give my opinion/recommendation next week.

**Comment by SueChaplain** [comment]
@smlambert  OMR is a jekyll website, as is Swift, so we've got experience of the set up. Most of the work is in creating a theme, but there are plenty out there you can customise.  My only sticking point with Jekyll is having another GitHub repo (Eclipse process / CQ for content & 3rd party tools etc) and then finding that it as difficult for people to contribute to as the existing website. If we are not going to go for Wordpress, perhaps it would be better to put effort into extending the website and adding a foolproof contribution guide.

**Comment by SueChaplain** [comment]
@llxia Interesting that you have heard bad stories about Wordpress. I took a quick look online and hosting your own does seem to have some "maintenance overhead" to keep the site patched. I guess that hosting on Wordpress.com has the advantage that someone else is handling all this for you.

**Comment by smlambert** [comment]
I guess its about ease of use, as we want low barrier of entry for developers to contribute content, and figure out where to put it.  Right now I don't feel we are there with the website, I am sitting on some content, because I don't really see where I could integrate it into the site.

In a blog style format, one doesn't have to think about where structurally content should live, one is merely sharing some idea to the world (often contextually related to time-based announcements, new release, new feature added, that doesn't necessarily have a home in a static website, unless you create a structure for those as you suggest, in terms of extending website).  

So yes, a conundrum...  

I would presume, after the one time tax of CQ, a blog repo would/should be owned/managed by dev teams, much like the code repos are today.

**Comment by SueChaplain** [comment]
We're definitely not there with the website as we only ever set out for it to be the shop window. 

If the debate comes down to money, then Jekyll is free. And a blog repo would be just another artifact that needs managing by contributors.

If the debate comes down to ease of use, Wordpress.com is probably the simplest solution.

**Comment by DanHeidinga** [comment]
This discussion seems to have bogged down a bit.

Let's give ourselves two weeks (until Wednesday April 18) to make a decision between Wordpress and Jekyll.

**Comment by mstoodle** [comment]
Is there anything we can learn from other project blogs?

**Comment by smlambert** [comment]
Sue mentioned that OMR project has a jekyll installation, but does not use it much.  I do not suspect this is a technical hurdle as much as time constraints thing, but perhaps you can weigh in there @mstoodle re:OMR?

Swift Kitura team use jekyll, worked through an initial learning/habit curve for blogging.  It looks pretty intuitive, I will try it out sometime this week.  

I happily use wordpress at Adopt and other websites, but I honestly do not have a strong opinion in either direction.  

I just want a way to share 'casual' project related content, like this feature went in this week and here are a few notes about it, etc.  The type of content that does not belong alongside the static website content like perf analysis, but is useful in that it can introduce new users to particular features or changes, or answer common questions (and then linked to from a /doc/test/faq.md or so forth.

**Comment by mstoodle** [comment]
@smlambert Yes, @SueChaplain and @charliegracie  set that up. It's a reasonably straight-forward workable flow; we have a sync job in our jenkins instance that takes care of moving the content over from the github repo to the Eclipse git instance, and then I believe jekyll runs automagically within about 10 minutes to update the actual site. It's not always smooth, but it's also true that we haven't been using it terribly much  *sigh* .

My personal blog site that @DanHeidinga mentioned earlier is just a fork of  https://github.com/barryclark/jekyll-now. It's pretty barebones but very easy to work with: you just drop an appropriately named .md file for each blog post into a directory and it automatically picks it up and incorporates into the generated site. Ok, now I'm hideously embarrassed by the dearth of content at that blog site <blush> .

Another possible option is to just let people write blog posts however and where ever they want, and just make it easy to add a new link to a relevant blog post. That isn't ideal either, but none of the options sound perfect and this one provides the most flexibility. It also handles reasonably smoothly a world where people other than the immediate OpenJ9 community can write about OpenJ9 without having to warp themselves into our chosen solution to the problem.

**Comment by deesebas** [comment]
For content other than 'What's new in OpenJ9', how about using a Medium Publication? 

Writers can publish Medium articles on wider topics related to OpenJ9, and request Openj9 Publication Editors to feature them (https://help.medium.com/hc/en-us/sections/203511997-General). It looks like some publication stats are available too (https://help.medium.com/hc/en-us/articles/215793317-Publication-stats).

For e.g. the Apache OpenWhisk community blog is https://medium.com/openwhisk

**Comment by smlambert** [comment]
Medium-backed blogs look nice, if I am not mistaken the content is kept at a central server, not under our control.  Not sure if that is something we want to consider.

For thoroughness, here is a summary of static webpage/blog generators (jekyll, middleman, roots, hugo):
https://www.smashingmagazine.com/2015/11/static-website-generators-jekyll-middleman-roots-hugo-review/#modern-static-website-technology

I am leaning towards jekyll if free is our motivation...

**Comment by SueChaplain** [comment]
Missed my opportunity for a final comment on todays OpenJ9 community call because Zoom was misbehaving for me.

This is a good resource for comparing static site generators. It's scary how many there are, but Jekyll is firmly in top spot, mainly because it is the default in GitHub: https://www.staticgen.com/

My opinion is based on funding.

If we have money -> Wordpress. 
*Paying for a site that is hosted for us, provides multi-user access, and google analytics would be the simplest option. Most people are familiar with Wordpress and it is very easy to create blogs, have them reviewed, and then post. A hosted solution also avoids the maintenance overhead of keeping up with patches.  Based on this we are looking at GBP20/mth: https://wordpress.com/#plans*

If we don't have money -> Jekyll

**Comment by DanHeidinga** [comment]
Thanks everyone for the comment and discussion.

> My opinion is based on funding. If we have money -> Wordpress.

This seems to be the consensus.  Let's proceed with securing funding for Wordpress and try that.  We can always migrate the data out of Wordpress later if this isn't meeting our needs / funding isn't available.

@smlambert you mentioned on Friday that you may be able to secure funding.  Were you successful?

**Comment by smlambert** [comment]
If by 'secure funding' you mean use my credit card then yes.  We are a go, I'll contact some of you as admins, and then we can add devs as editors and get the ball rolling later this week.

**Comment by DanHeidinga** [comment]
Thanks @smlambert!

**Comment by SueChaplain** [comment]
Closing this issue as we now have https://blogopenj9.wordpress.com/. Thanks @smlambert 
New issue #80 opened for integrating this into our existing shop window.
