### ISSUE TITLE
Thank you page for build farm sponsors

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-website#74]
OpenJ9's CI builds are powered by donated machines.  We should be publicly thanking the providers of those machines on website.

**Comment by SueChaplain** [comment]
@DanHeidinga is there somewhere you can point me that says who donated what please? I know that IBM donated some machines, but not sure all came from IBM. Thanks

**Comment by DanHeidinga** [comment]
@mstoodle were you involved with getting the p & z Linux machines?  Can you supply details on who is providing them?

@xliang6 Can you comment on who's providing the AIX machines?

The 4 new windows machines are from IBM.

**Comment by xliang6** [comment]
@DanHeidinga @SueChaplain AIX machines are from IBM. Thanks.

**Comment by mstoodle** [comment]
@DanHeidinga There's a paragraph in my blog from way back in september: https://mstoodle.github.io/OpenJ9-2weeks/

See the paragraph starting "On that front..."

**Comment by AdamBrousseau** [comment]
Perhaps for the AIX and Windows machines we should elaborate more on how IBM has provided them? The AIX ones come from the [Power Development Platfotm](https://www-356.ibm.com/partnerworld/wps/servlet/ContentHandler/stg_com_sys_power-development-platform). I believe the Windows ones come from Softlayer.

**Comment by SueChaplain** [comment]
Website redesign About page includes thanks for sponsors.
