### ISSUE TITLE
Create new page for support statement

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#79]
Following the discussion and votes in https://github.com/eclipse/openj9/issues/1616.

**Comment by SueChaplain** [comment]
Note: Target placement for this is in the user doc rather than the website, where it can be updated more easily by contributors. If the User doc is available ahead of the 0.9.0 release, the page will be created there directly.

**Comment by SueChaplain** [comment]
First pass at writing up Mark's support statement and creating the version-specific tables. Please can people comment, particularly on the platform support section where the tables are missing information and comments. We need to confirm build platform levels, compiler levels, whether something is "in progress" or  "from OpenJ9v 0.8.0 and later" etc etc. 
@mstoodle @DanHeidinga @pshipton @vsebe @JamesKingdon @keithc-ca 

# Supported environments

The Eclipse OpenJ9 project source code can be built against multiple JDK levels starting with JDK8, so the question of support has a more complicated answer than at OpenJDK. Our community is committed to supporting JDK levels as long as they are supported at the OpenJDK open source project with a significant user base. Currently, Eclipse OpenJ9 produces a new release every quarter that can build against all JDK levels currently supported by the OpenJDK community. We are committed to accepting problem reports when using Eclipse OpenJ9 against a supported OpenJDK level, with fixes being delivered in each release of Eclipse OpenJ9.

The following table summarizes which JDK levels are expected to be supported by which Eclipse OpenJ9 releases, along with projected release dates. All future dates and support expectations are predictions that might change depending on how the OpenJDK and OpenJ9 projects evolve over time. Note also that columns may be removed from this table over time. For example, JDK9 will be removed from this table shortly because it will no longer be supported by any open project.


## Eclipse OpenJ9 releases

| OpenJ9 release  | Release date       | JDK8 (LTS)| JDK9 | JDK10 | JDK11 (LTS) | JDK12 | JDK13 |
|-----------------|--------------------|-----------|------|-------|-------------|-------|-------|
| v0.8.0          | March 2018         | Yes       | No   |       |             |       |       |
| v0.9.0          | May 2018 (\*1)     | Yes       | No   | ?     |             |       |       |
| v0.10.0         | August 2018 (\*2)  | Yes       | No   | Yes   |             |       |       |
| v0.11.0         | October 2018 (\*2) | Yes       | No   | No    | Yes         |       |       |
| v0.12.0         | January 2019 (\*2) | Yes       | No   | No    | Yes         |       |       |
| v0.13.0         | April 2019 (\*2)   | No (\*3)  | No   | No    | No (\*3)    | Yes   |       |
| v0.14.0         | July 2019 (\*2)    | No (\*3)  | No   | No    | No (\*3)    | Yes   |       |
| v0.15.0         | October 2019 (\*2) | No (\*3)  | No   | No    | No (\*3)    | No    | Yes   |


**Notes:**

- (\*1): This OpenJ9 release is in plan.
- (\*2): These OpenJ9 releases are expected, in line with our support statement.
- (\*3): We fully expect that OpenJDK8 will have open community maintainers beyond January 2019, so we expect to be able to continue supporting JDK8 beyond that date. Until maintainers have been established we are unable to make a definitive support statement. This position is the same for JDK11 and all future "LTS" releases.

## Platform support

The Eclipse OpenJ9 project is open to supporting any hardware/operating system platforms provided that we have community members available to maintain them. For practical reasons the Eclipse OpenJ9 JVM does not currently run on every platform. The following tables show the minimum build configurations that we have tested to build an OpenJDK binary.

For any issues or limitations of an Eclipse OpenJ9 release, read the release notes:

- [OpenJ9 0.8.0 release notes](https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.8/0.8.md)
- [OpenJ9 0.9.0 release notes](https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.9/0.9.md)

**NOTE:** If you obtain pre-built binaries from [AdoptOpenJDK.net](https://adoptopenjdk.net/index.html), platform support might vary, depending on their build environment.

### OpenJDK 8 build environment

| Platform                    | Operating system          |  Compiler                       |  Comments      |
|-----------------------------|---------------------------|---------------------------------|----------------|
| Linux x86 64-bit            | Ubuntu 12.04              | gcc 4.8.4                       |                |
| Linux on POWER LE 64-bit    | Ubuntu 12.04              | gcc 4.8.4                       |                |
| Linux on IBM Z 64-bit       | Ubuntu 12.04              | gcc 4.8.4                       |                |
| Windows x86 64-bit          | Windows Server 2012       | Microsoft Visual Studio 2010 SP1|                |
| AIX POWER BE 64-bit         | AIX 7.1                   | xlc/C++ 13.1.3                  |                |
| MacOS on X86 64-bit         | MacOS 10.10               | ?                               |                |
| ARM on x86 32-bit           | Raspian 8                 | ?                               |                |

OpenJDK8 binaries are supported on the minimum operating system levels shown in the table. For Linux, other distributions are supported provided that they have a Linux kernel v3.2 or later (Look in the `/proc/version` file to find the kernel version number).

### OpenJDK 9 build environment

| Platform                    | Operating system         |  Compiler                       |   Comments     |
|-----------------------------|--------------------------|---------------------------------|----------------|
| Linux x86 64-bit            | Ubuntu 16.04 (kernel 4.4)| gcc 4.8.4                       |                |
| Linux on POWER LE 64-bit    | Ubuntu 16.04             | gcc 4.8.4                       |                |
| Linux on IBM Z 64-bit       | Ubuntu 16.04             | gcc 4.8.4                       |                |
| Windows x86 64-bit          | Windows Server 2016      | Microsoft Visual Studio 2013    |                |
| AIX POWER BE 64-bit         | AIX 7.1                  | xlc/C++ 13.1.3                  |                |
| MacOS on X86 64-bit         | MacOS 10.10              | ?                               |                |
| ARM on x86 32-bit           | Raspian 8                | ?                               |                |

OpenJDK9 binaries are supported on the minimum operating system levels shown in the table. For Linux, other distributions are supported provided that they have a Linux kernel v4.4 or later (Look in the `/proc/version` file to find the kernel version number).

### OpenJDK 10 build environment

| Platform                    | Operating system         |  Compiler                       |   Comments     |
|-----------------------------|--------------------------|---------------------------------|----------------|
| Linux x86 64-bit            | Ubuntu 16.04             | gcc 4.8.4                       |                |
| Linux on POWER LE 64-bit    | Ubuntu 16.04             | gcc 4.8.4                       |                |
| Linux on IBM Z 64-bit       | Ubuntu 16.04             | gcc 4.8.4                       |                |
| Windows x86 64-bit          | Windows Server 2016      | Microsoft Visual Studio 2010 SP1|                |
| AIX POWER BE 64-bit         | AIX 7.2                  | xlc/C++ 13.1.3                  |                |
| MacOS on X86 64-bit         | MacOS 10.10              | ?                               |                |
| ARM on x86 32-bit           | Raspian 8                | ?                               |                |

OpenJDK10 binaries are supported on the minimum operating system levels shown in the table. For Linux, other distributions are supported provided that they have a Linux kernel v4.4 or later (Look in the `/proc/version` file to find the kernel version number).

**Comment by pshipton** [comment]
JDK10 support for "compatibility (but not compliance)" is in plan for OpenJ9 0.9.0 https://projects.eclipse.org/projects/technology.openj9/releases/0.9.0. I think the table should show Yes.

- Since there is no working OpenJ9 build for MacOS yet, suggest the MacOS line be removed until there is
- Ubuntu 12.04 is out of support, I think Java 8 levels should be at Ubuntu 14.04
- Suggest TL04 as the minimum level for AIX 7.1

**Comment by pshipton** [comment]
Should there be a statement that OpenJ9 is only supported on OSes which are publicly supported?

**Comment by JamesKingdon** [comment]
Do we want to put the ARM rows in yet, given that there are still no official builds? If we do we need to figure out how to distinguish between the environment that the JVM runs on (e.g. Linux on armhf/aarch64) and the environment that it builds in (Ubuntu 16.04 on x86 64-bit).

**Comment by keithc-ca** [comment]
Shouldn't the OpenJDK 10 build environment on Windows require Microsoft Visual Studio 2013 like OpenJDK 9?

**Comment by SueChaplain** [comment]
My entry is updated to address all comments from @keithc-ca @pshipton and @JamesKingdon. Any further comments please?

**Comment by pshipton** [comment]
+1

@mstoodle @DanHeidinga any comments?

**Comment by keithc-ca** [comment]
+1

**Comment by JamesKingdon** [comment]
Looks good.

**Comment by mstoodle** [comment]
+1

**Comment by DanHeidinga** [comment]
+1

I'm glad to see this was mentioned:
> NOTE: If you obtain pre-built binaries from AdoptOpenJDK.net, platform support might vary, depending on their build environment.

We should work with Adopt to modify the build OSes to match our support levels where possible or to build on an OS with an older glibc so it will run on newer platforms.
