### ISSUE TITLE
FAQ probably doesn't need to be collapsed by default

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9-website#8]
Though, as it gets longer, maybe a table of contents would be nice.

**Comment by SueChaplain** [comment]
I think collapsing them is the right thing to do so that people can peruse the list for a question they are interested in, rather than scrolling.  Having them in this style means we don't need to create a table to summarise them?

We're open to changing things if there is a consensus.

**Comment by doveye** [comment]
We can reopen if there is a consensus to change what's currently there
