### ISSUE TITLE
Add link / integration for new Wordpress blog

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#80]
New wordpress site now created by Shelley for OpenJ9 blogs: https://blogopenj9.wordpress.com/

- We need links on the website to the blog
- We need to think about how to tie the sites together. They don't need to look identical, but they should blend so that they have a consistent "brand".

**Comment by smlambert** [comment]
Thanks @SueChaplain, note that blog.openj9.org is probably the public link you will wish to use and display.  It resolves to blogopenj9.wordpress.com (a URL that will eventually be unseen).

I have not spent time looking for a theme to visually tie the blog and website together (agree they do not have to look identical), but was going to find a theme that was simple yet not as simple as the one currently in place for the blog.

**Comment by SueChaplain** [comment]
Suggest:

- we add a what's new introducing the blog.
- add "Blog" to the menu bar, linking directly to blog.openj9.org.
- Update the "Resources" page to provide the blog site as another resource.

Any other ideas, please add.

**Comment by ashu-mehra** [comment]
@SueChaplain Link to blog page on https://www.eclipse.org/openj9/oj9_whatsnew.html points to same page again.

**Comment by SueChaplain** [comment]
@ashu-mehra - fixed, thanks!
