### ISSUE TITLE
Adapt website colour palette to blend with Eclipse Foundation

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#91]
Eclipse Foundation colours have changed to differentiate it from the Eclipse IDE, which means moving away from the purple/teal/orange that were selected for OpenJ9. 

Due to GDPR compliance all Eclipse projects must now use a common privacy popup, which uses the new Eclipse Foundation colours. The new colours do not sit well with the old colours!

We need to come up with a palette that blends with the Eclipse Foundation so that the common popup does not look at odds with the OpenJ9 site and that we do not confuse people by staying with the IDE palette.

**Comment by pmhayward** [comment]
Attached are two sample screen shots that demonstrate the proposed colour palette that's been revised to be compatible with the new Eclipse Foundation style. The 'build' page image also shows the Eclipse cookies notice that will appear on OpenJ9 pages.

![openj9-revisedcss-home](https://user-images.githubusercontent.com/20087447/40168974-ca46524c-59bc-11e8-9a24-fd8e787696a9.png)

![openj9-revisedcss-build](https://user-images.githubusercontent.com/20087447/40168991-d954dd58-59bc-11e8-80ae-26d060888157.png)

**Comment by SueChaplain** [comment]
@mstoodle @DanHeidinga @pshipton 

Please +1 if you are happy with these changes or post some comments. The changes largely replace purple with black, and match the shade of Orange so that the popup privacy policy required by GDPR is not at odds with the website.

**Comment by pshipton** [comment]
+1

**Comment by DanHeidinga** [comment]
+1

**Comment by SueChaplain** [comment]
@mstoodle Are you ok with this too please?

**Comment by smlambert** [comment]
I should mention that we are ditching the orange from the blog site... it tests very poorly with a large percentage of developers (who are our target audience for the blog).  I fully understand that the website likely has to adhere to a certain colour palette, but we do not wish to go so fully orange on the "for developers, by developers" blog site.

Though I do have to say, I like this revision you are presenting here, thanks @SueChaplain !

**Comment by SueChaplain** [comment]
We have a majority vote +1, so these changes will be rolling in soon in order to have our GDPR policy popup live and blending.
@smlambert  interesting that orange is not a "hip" colour for developers. Where did you find out about that? Perhaps that should be fed through to Eclipse :-)
