### ISSUE TITLE
Replace shared classes artitle

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-website#98]
We have a new shared classes article published here: 
https://www.ibm.com/developerworks/library/j-class-sharing-openj9/

The page https://www.eclipse.org/openj9/oj9_resources.html is pointing to the out-of-date articles ( Class sharing,  Enhance performance with class sharing). They need to fixed to point to the new article.

**Comment by SueChaplain** [comment]
We're unable to update the site at the moment but have a bugzilla open with Eclipse to fix. As soon as that is done we'll update the page.

Shame we're not pointing to this from the recent Eclipse newsletter and JaxEnter articles.
